### ISSUE TITLE
[Repo] Support custom metadata

### ISSUE THREAD

**Issue by bratfizyk** [haf/EventStore.Client.FSharp#1]
Hi,

I've been giving a try to the library and it looks promising. 
There's an issue that I don't really understand: when I use Repo.make, is there a way of adding my own metadata to a function that commits to a stream ? I found the following piece of code:

    let commit (serialise : obj -> _) conn (id, expected : ExpectedVersionUnion) (es : 'a list) =

        let commitHeaders = [ CommitIdKey, box(Guid.NewGuid ()) ] |> Map.ofList
        let streamId = streamId id

        let prepareData headers (e : 'a) =
          let headers' = headers |> Map.add EventTypeKey (typeof<'a>.ToPartiallyQualifiedName() |> box)
          let eventType, data = serialise e
          let _, metaData = serialise headers'
          { Id       = Guid.NewGuid()
            Type     = eventType // this is the 'semantic name', see TypeNaming.name.
            Data     = data
            Metadata = metaData
            IsJson   = true }

    ...

and looks like metadata set is hardcoded.
I'd be happy to be able to include e.g. Transaction Time in metadata.

**Comment by haf** [comment]
I'm re-making the domain-side of things into its own lib, ReCQ, which will also include APIs for handling HTTP requests and executing them on domain objects, as well as unit testing domain models. The Repo module is being moved there, too.

As a part of that I might fix this issue while I'm in the code.

I'm also going to make 'category' explicit, so that the StreamId is not just an opaque `entity-123456`, but instead a tuple of category `entity` and an id `123456`, which will also suit web APIs better.

**Comment by haf** [comment]
This is done in the latest beta. Closing.
