### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Kurren-N** [haf/EventStore.Client.FSharp#10]
Is this project dead? Has event store with F# gone out of fashion now or is there another library that's being used instead of this nowadays?

Thanks!

**Comment by haf** [comment]
Hi,

It's not dead, I'm still using it. It's also stable.

Keep your eyed peeled to [ReCQ](https://github.com/recq/recq) though, as we'll publish a major framework built on top of this, there, in the close future.

**Comment by o1lo01ol1o** [comment]
Pinging on the status of this repo.  Are there plans to support v4?

**Comment by haf** [comment]
Hello Tim,

I couldn't justify the time expense in keeping it maintained publicly in the end, also because there were noone who helped me maintain it. We have a private continuation of this library that is also a stream processing library implementation on top of ES, that I could sell you; it's up to date with 3.9.4 and well tested.

Regards, Henrik
